package commands

import "fmt"

// PrintUsage displays the main CLI usage information
func PrintUsage() {
	fmt.Println("NetBird Management CLI")
	fmt.Println("----------------------")
	fmt.Println("A simple tool to manage your NetBird network via the API.")
	fmt.Println("\nUsage:")
	fmt.Println("  netbird-manage [--yes] [--debug] <command> [arguments]")
	fmt.Println("\nGlobal Flags:")
	fmt.Println("  --yes, -y                     Skip confirmation prompts (for automation)")
	fmt.Println("  --debug, -d                   Enable verbose debug output (HTTP requests/responses)")
	fmt.Println("\nAvailable Commands:")
	fmt.Println("  connect                       Check current connection status")
	fmt.Println("  connect [flags]               Connect and save your API token")
	fmt.Println("    --token <key>               (Required) Your NetBird API token")
	fmt.Println("    --management-url <url>      (Optional) Your self-hosted management URL")
	fmt.Println()
	fmt.Println("  peer ...                      Manage peers (run 'netbird-manage peer' for options)")
	fmt.Println()
	fmt.Println("  group ...                     Manage groups (run 'netbird-manage group' for options)")
	fmt.Println()
	fmt.Println("  network ...                   Manage networks (run 'netbird-manage network' for options)")
	fmt.Println()
	fmt.Println("  policy ...                    Manage access control policies (run 'netbird-manage policy' for options)")
	fmt.Println()
	fmt.Println("  setup-key ...                 Manage device registration keys (run 'netbird-manage setup-key' for options)")
	fmt.Println()
	fmt.Println("  user ...                      Manage users and invitations (run 'netbird-manage user' for options)")
	fmt.Println()
	fmt.Println("  token ...                     Manage personal access tokens (run 'netbird-manage token' for options)")
	fmt.Println()
	fmt.Println("  route ...                     Manage network routes (run 'netbird-manage route' for options)")
	fmt.Println()
	fmt.Println("  dns ...                       Manage DNS nameserver groups (run 'netbird-manage dns' for options)")
	fmt.Println()
	fmt.Println("  posture-check ...             Manage device posture checks (run 'netbird-manage posture-check' for options)")
	fmt.Println()
	fmt.Println("  event ...                     View audit logs and network traffic events (run 'netbird-manage event' for options)")
	fmt.Println()
	fmt.Println("  geo ...                       Retrieve geographic location data (run 'netbird-manage geo' for options)")
	fmt.Println()
	fmt.Println("  account ...                   Manage account settings (run 'netbird-manage account' for options)")
	fmt.Println()
	fmt.Println("  ingress-port ...              Manage port forwarding - Cloud-only (run 'netbird-manage ingress-port' for options)")
	fmt.Println()
	fmt.Println("  ingress-peer ...              Manage ingress peers - Cloud-only (run 'netbird-manage ingress-peer' for options)")
	fmt.Println()
	fmt.Println("  export ...                    Export configuration to YAML (run 'netbird-manage export' for options)")
	fmt.Println()
	fmt.Println("  import ...                    Import configuration from YAML (run 'netbird-manage import' for options)")
	fmt.Println()
	fmt.Println("  help                          Show this help message")
}

// PrintPeerUsage provides specific help for the 'peer' command
func PrintPeerUsage() {
	fmt.Println("Usage: netbird-manage peer <flag> [arguments]")
	fmt.Println("\nManage network peers.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                            List all peers")
	fmt.Println("    --filter-name <pattern>         Filter by name (supports wildcards: ubuntu*)")
	fmt.Println("    --filter-ip <pattern>           Filter by IP address pattern")
	fmt.Println("  --inspect <peer-id>               Inspect a single peer")
	fmt.Println("  --accessible-peers <peer-id>      List peers accessible from the specified peer")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --remove <peer-id>                Remove a peer from your network")
	fmt.Println("  --remove-batch <id1,id2,...>      Remove multiple peers (comma-separated IDs)")
	fmt.Println()
	fmt.Println("  --edit <peer-id>                  Edit peer group membership")
	fmt.Println("    --add-group <group-id>          Add peer to a group (requires --edit)")
	fmt.Println("    --remove-group <group-id>       Remove peer from a group (requires --edit)")
	fmt.Println()
	fmt.Println("  --update <peer-id>                Update peer settings")
	fmt.Println("    --rename <new-name>             Change peer name")
	fmt.Println("    --ssh-enabled <true|false>      Enable/disable SSH access")
	fmt.Println("    --login-expiration <true|false> Enable/disable login expiration")
	fmt.Println("    --inactivity-expiration <true|false> Enable/disable inactivity expiration")
	fmt.Println("    --approval-required <true|false> Require approval (cloud-only)")
	fmt.Println("    --ip <ip-address>               Set IP (must be in 100.64.0.0/10 range)")
}

// PrintGroupUsage provides specific help for the 'group' command
func PrintGroupUsage() {
	fmt.Println("Usage: netbird-manage group <flag> [arguments]")
	fmt.Println("\nManage network groups.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all groups")
	fmt.Println("    --filter-name <pattern>        Filter by name (supports wildcards: prod-*)")
	fmt.Println("  --inspect <group-id>             Inspect a specific group")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <group-name>            Create a new group")
	fmt.Println("    --peers <id1,id2,...>          (Optional) Add peers on creation")
	fmt.Println()
	fmt.Println("  --delete <group-id>              Delete a group")
	fmt.Println("  --delete-batch <id1,id2,...>     Delete multiple groups (comma-separated IDs)")
	fmt.Println("  --delete-unused                  Delete all unused groups (no peers, resources, or references)")
	fmt.Println()
	fmt.Println("  --rename <group-id>              Rename a group")
	fmt.Println("    --new-name <new-name>          New name for the group (required)")
	fmt.Println()
	fmt.Println("  --add-peers <group-id>           Add peers to a group (bulk)")
	fmt.Println("    --peers <id1,id2,...>          Comma-separated peer IDs (required)")
	fmt.Println()
	fmt.Println("  --remove-peers <group-id>        Remove peers from a group (bulk)")
	fmt.Println("    --peers <id1,id2,...>          Comma-separated peer IDs (required)")
}

// PrintNetworkUsage provides specific help for the 'network' command
func PrintNetworkUsage() {
	fmt.Println("Usage: netbird-manage network <flag> [arguments]")
	fmt.Println("\nManage networks, resources, and routers.")
	fmt.Println("\n=== Network Operations ===")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                              List all networks")
	fmt.Println("    --filter-name <pattern>           Filter by name (supports wildcards: prod-*)")
	fmt.Println("  --inspect <network-id>              Inspect a specific network")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                     Create a new network")
	fmt.Println("    --description <desc>              Network description (optional)")
	fmt.Println()
	fmt.Println("  --delete <network-id>               Delete a network")
	fmt.Println()
	fmt.Println("  --rename <network-id>               Rename a network")
	fmt.Println("    --new-name <name>                 New name (required)")
	fmt.Println()
	fmt.Println("  --update <network-id>               Update network description")
	fmt.Println("    --description <desc>              New description (required)")
	fmt.Println()
	fmt.Println("\n=== Resource Operations ===")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list-resources <network-id>       List all resources in a network")
	fmt.Println("  --inspect-resource                  Inspect a specific resource")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --resource-id <id>                Resource ID (required)")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --add-resource <network-id>         Add a resource to a network")
	fmt.Println("    --name <name>                     Resource name (required)")
	fmt.Println("    --address <address>               IP (1.1.1.1), subnet (192.168.0.0/24), or domain (*.example.com) (required)")
	fmt.Println("    --groups <id1,id2,...>            Comma-separated group IDs (required)")
	fmt.Println("    --description <desc>              Resource description (optional)")
	fmt.Println("    --enabled                         Enable resource (default)")
	fmt.Println("    --disabled                        Disable resource")
	fmt.Println()
	fmt.Println("  --update-resource                   Update a resource")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --resource-id <id>                Resource ID (required)")
	fmt.Println("    --name <name>                     New name (optional)")
	fmt.Println("    --address <address>               New address (optional)")
	fmt.Println("    --groups <id1,id2,...>            New groups (optional)")
	fmt.Println("    --description <desc>              New description (optional)")
	fmt.Println("    --enabled/--disabled              Toggle enabled status")
	fmt.Println()
	fmt.Println("  --remove-resource                   Remove a resource")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --resource-id <id>                Resource ID (required)")
	fmt.Println()
	fmt.Println("\n=== Router Operations ===")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list-routers <network-id>         List all routers in a network")
	fmt.Println("  --list-all-routers                  List all routers across all networks")
	fmt.Println("  --inspect-router                    Inspect a specific router")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --router-id <id>                  Router ID (required)")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --add-router <network-id>           Add a router to a network")
	fmt.Println("    --peer <peer-id>                  Use single peer as router (use this OR --peer-groups)")
	fmt.Println("    --peer-groups <id1,id2,...>       Use peer groups as routers (use this OR --peer)")
	fmt.Println("    --metric <1-9999>                 Route metric, lower = higher priority (default: 100)")
	fmt.Println("    --masquerade                      Enable masquerading (NAT)")
	fmt.Println("    --no-masquerade                   Disable masquerading (default)")
	fmt.Println("    --enabled                         Enable router (default)")
	fmt.Println("    --disabled                        Disable router")
	fmt.Println()
	fmt.Println("  --update-router                     Update a router")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --router-id <id>                  Router ID (required)")
	fmt.Println("    --peer <peer-id>                  Change to single peer (optional)")
	fmt.Println("    --peer-groups <id1,id2,...>       Change to peer groups (optional)")
	fmt.Println("    --metric <1-9999>                 Update metric (optional)")
	fmt.Println("    --masquerade/--no-masquerade      Toggle masquerading")
	fmt.Println("    --enabled/--disabled              Toggle enabled status")
	fmt.Println()
	fmt.Println("  --remove-router                     Remove a router")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --router-id <id>                  Router ID (required)")
}

// PrintPolicyUsage provides specific help for the 'policy' command
func PrintPolicyUsage() {
	fmt.Println("Usage: netbird-manage policy <flag> [arguments]")
	fmt.Println("\nManage access control policies.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all policies")
	fmt.Println("  --inspect <policy-id>            Inspect a specific policy")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create a new policy")
	fmt.Println("    --description <desc>           Policy description (optional)")
	fmt.Println("    --enabled                      Enable policy (default)")
	fmt.Println("    --disabled                     Create disabled policy")
	fmt.Println()
	fmt.Println("  --delete <policy-id>             Delete a policy")
	fmt.Println()
	fmt.Println("  --enable <policy-id>             Enable a policy")
	fmt.Println("  --disable <policy-id>            Disable a policy")
	fmt.Println()
	fmt.Println("  --add-rule <policy-id>           Add a rule to a policy")
	fmt.Println("    --rule-name <name>             Rule name (required)")
	fmt.Println("    --sources <groups>             Source group IDs/names (comma-separated)")
	fmt.Println("    --destinations <groups>        Destination group IDs/names (comma-separated)")
	fmt.Println("    --protocol <protocol>          Protocol: all, tcp, udp, icmp (default: all)")
	fmt.Println("    --ports <ports>                Ports: 80,443 or 8000-9000 (optional)")
	fmt.Println("    --action <action>              Action: accept or drop (default: accept)")
	fmt.Println("    --bidirectional                Enable bidirectional traffic (default)")
	fmt.Println("    --unidirectional               Disable bidirectional traffic")
}

// PrintSetupKeyUsage provides specific help for the 'setup-key' command
func PrintSetupKeyUsage() {
	fmt.Println("Usage: netbird-manage setup-key <flag> [arguments]")
	fmt.Println("\nManage device registration/setup keys.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all setup keys")
	fmt.Println("  --inspect <key-id>               Inspect a specific setup key")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create a new setup key")
	fmt.Println("    --type <type>                  Key type: one-off or reusable (default: one-off)")
	fmt.Println("    --expires-in <days>            Expiration in days (default: 30)")
	fmt.Println("    --usage-limit <limit>          Max uses for reusable keys (default: 0 = unlimited)")
	fmt.Println("    --auto-groups <groups>         Comma-separated group IDs/names for auto-assignment")
	fmt.Println("    --ephemeral                    Create ephemeral peers (auto-removed when offline)")
	fmt.Println()
	fmt.Println("  --quick-create                   Quickly create a one-off key with defaults")
	fmt.Println("    --auto-groups <groups>         (Optional) Auto-assign groups")
	fmt.Println()
	fmt.Println("  --delete <key-id>                Delete a setup key")
	fmt.Println("  --delete-batch <id1,id2,...>     Delete multiple keys (comma-separated IDs)")
	fmt.Println("  --delete-all                     Delete ALL setup keys (requires confirmation)")
	fmt.Println()
	fmt.Println("  --revoke <key-id>                Revoke a setup key (disable without deleting)")
}

// PrintUserUsage provides specific help for the 'user' command
func PrintUserUsage() {
	fmt.Println("Usage: netbird-manage user <flag> [arguments]")
	fmt.Println("\nManage users and access.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all users")
	fmt.Println("  --inspect <user-id>              Inspect a specific user")
	fmt.Println("  --me                             Show current user info")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --invite <email>                 Invite a new user")
	fmt.Println("    --role <role>                  Role: admin, user, owner (default: user)")
	fmt.Println("    --auto-groups <groups>         Comma-separated group IDs for auto-assignment")
	fmt.Println()
	fmt.Println("  --create-service <name>          Create a service user")
	fmt.Println("    --role <role>                  Role: admin, user (default: user)")
	fmt.Println("    --auto-groups <groups>         Comma-separated group IDs for auto-assignment")
	fmt.Println()
	fmt.Println("  --update <user-id>               Update a user")
	fmt.Println("    --role <role>                  New role")
	fmt.Println("    --auto-groups <groups>         New auto-groups")
	fmt.Println()
	fmt.Println("  --block <user-id>                Block a user")
	fmt.Println("  --unblock <user-id>              Unblock a user")
	fmt.Println()
	fmt.Println("  --remove <user-id>               Remove a user")
	fmt.Println("  --resend-invite <user-id>        Resend invitation email")
}

// PrintTokenUsage provides specific help for the 'token' command
func PrintTokenUsage() {
	fmt.Println("Usage: netbird-manage token <flag> [arguments]")
	fmt.Println("\nManage personal access tokens.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all tokens for current user")
	fmt.Println("  --inspect <token-id>             Inspect a specific token")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create a new token")
	fmt.Println("    --expires-in <days>            Expiration in days (1-365, default: 30)")
	fmt.Println()
	fmt.Println("  --revoke <token-id>              Revoke/delete a token")
}

// PrintRouteUsage provides specific help for the 'route' command
func PrintRouteUsage() {
	fmt.Println("Usage: netbird-manage route <flag> [arguments]")
	fmt.Println("\nManage network routes.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all routes")
	fmt.Println("  --inspect <route-id>             Inspect a specific route")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create                         Create a new route")
	fmt.Println("    --network-id <id>              Route identifier (required)")
	fmt.Println("    --network <cidr>               Network CIDR (required, e.g., 10.0.0.0/16)")
	fmt.Println("    --peer <peer-id>               Routing peer (use this OR --peer-groups)")
	fmt.Println("    --peer-groups <ids>            Routing peer groups (comma-separated)")
	fmt.Println("    --groups <ids>                 Distribution groups (comma-separated, required)")
	fmt.Println("    --metric <1-9999>              Route metric (default: 100)")
	fmt.Println("    --masquerade                   Enable masquerading")
	fmt.Println("    --description <desc>           Route description")
	fmt.Println()
	fmt.Println("  --delete <route-id>              Delete a route")
	fmt.Println()
	fmt.Println("  --enable <route-id>              Enable a route")
	fmt.Println("  --disable <route-id>             Disable a route")
}

// PrintDNSUsage provides specific help for the 'dns' command
func PrintDNSUsage() {
	fmt.Println("Usage: netbird-manage dns <flag> [arguments]")
	fmt.Println("\nManage DNS nameserver groups.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all DNS nameserver groups")
	fmt.Println("  --inspect <group-id>             Inspect a specific DNS group")
	fmt.Println("  --settings                       Show DNS settings")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create a DNS nameserver group")
	fmt.Println("    --nameservers <ips>            Comma-separated nameserver IPs (required)")
	fmt.Println("    --groups <ids>                 Distribution groups (comma-separated, required)")
	fmt.Println("    --domains <domains>            Match domains (comma-separated, optional)")
	fmt.Println("    --primary                      Set as primary DNS")
	fmt.Println("    --search-domains               Enable search domains")
	fmt.Println()
	fmt.Println("  --delete <group-id>              Delete a DNS nameserver group")
	fmt.Println()
	fmt.Println("  --enable <group-id>              Enable a DNS group")
	fmt.Println("  --disable <group-id>             Disable a DNS group")
}

// PrintPostureCheckUsage provides specific help for the 'posture-check' command
func PrintPostureCheckUsage() {
	fmt.Println("Usage: netbird-manage posture-check <flag> [arguments]")
	fmt.Println("\nManage device posture checks.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all posture checks")
	fmt.Println("  --inspect <check-id>             Inspect a specific posture check")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create a posture check")
	fmt.Println("    --description <desc>           Check description")
	fmt.Println("    --nb-version <version>         Minimum NetBird version")
	fmt.Println("    --geo-allow <codes>            Allow countries (comma-separated ISO codes)")
	fmt.Println("    --geo-deny <codes>             Deny countries")
	fmt.Println("    --network-allow <cidrs>        Allow network ranges")
	fmt.Println("    --network-deny <cidrs>         Deny network ranges")
	fmt.Println()
	fmt.Println("  --delete <check-id>              Delete a posture check")
}

// PrintEventUsage provides specific help for the 'event' command
func PrintEventUsage() {
	fmt.Println("Usage: netbird-manage event <flag> [arguments]")
	fmt.Println("\nView audit logs and network traffic events.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List recent audit events")
	fmt.Println("    --user-id <id>                 Filter by user ID")
	fmt.Println("    --activity <code>              Filter by activity code")
	fmt.Println("    --start-date <date>            Start date (YYYY-MM-DD)")
	fmt.Println("    --end-date <date>              End date (YYYY-MM-DD)")
	fmt.Println()
	fmt.Println("  --traffic                        List network traffic events (Cloud-only)")
	fmt.Println("    --page <n>                     Page number")
	fmt.Println("    --page-size <n>                Results per page")
	fmt.Println()
	fmt.Println("  --json                           Output in JSON format")
}

// PrintGeoLocationUsage provides specific help for the 'geo' command
func PrintGeoLocationUsage() {
	fmt.Println("Usage: netbird-manage geo <flag> [arguments]")
	fmt.Println("\nRetrieve geographic location data for posture checks.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --countries                      List all available country codes")
	fmt.Println("  --cities <country-code>          List cities for a country (e.g., --cities US)")
	fmt.Println()
	fmt.Println("  --json                           Output in JSON format")
}

// PrintAccountUsage provides specific help for the 'account' command
func PrintAccountUsage() {
	fmt.Println("Usage: netbird-manage account <flag> [arguments]")
	fmt.Println("\nManage account settings.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all accounts")
	fmt.Println("  --inspect <account-id>           Inspect account settings")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --update <account-id>            Update account settings")
	fmt.Println("    --peer-login-expiration <s>    Peer login expiration in seconds")
	fmt.Println("    --peer-inactivity-expiration <s> Peer inactivity expiration in seconds")
	fmt.Println()
	fmt.Println("  --delete <account-id>            Delete an account (dangerous!)")
}

// PrintIngressPortUsage provides specific help for the 'ingress-port' command
func PrintIngressPortUsage() {
	fmt.Println("Usage: netbird-manage ingress-port <flag> [arguments]")
	fmt.Println("\nManage port forwarding (Cloud-only).")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list <peer-id>                 List ingress ports for a peer")
	fmt.Println("  --inspect                        Inspect a specific port allocation")
	fmt.Println("    --peer-id <id>                 Peer ID (required)")
	fmt.Println("    --port-id <id>                 Port allocation ID (required)")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <peer-id>               Create a port forwarding rule")
	fmt.Println("    --target-port <port>           Target port on the peer (required)")
	fmt.Println("    --protocol <tcp|udp>           Protocol (default: tcp)")
	fmt.Println("    --description <desc>           Description")
	fmt.Println()
	fmt.Println("  --delete                         Delete a port allocation")
	fmt.Println("    --peer-id <id>                 Peer ID (required)")
	fmt.Println("    --port-id <id>                 Port allocation ID (required)")
}

// PrintIngressPeerUsage provides specific help for the 'ingress-peer' command
func PrintIngressPeerUsage() {
	fmt.Println("Usage: netbird-manage ingress-peer <flag> [arguments]")
	fmt.Println("\nManage ingress peers (Cloud-only).")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all ingress peers")
	fmt.Println("  --inspect <peer-id>              Inspect a specific ingress peer")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create an ingress peer")
	fmt.Println("    --location <location>          Geographic location")
	fmt.Println("    --enabled                      Enable on creation (default)")
	fmt.Println()
	fmt.Println("  --delete <peer-id>               Delete an ingress peer")
	fmt.Println()
	fmt.Println("  --enable <peer-id>               Enable an ingress peer")
	fmt.Println("  --disable <peer-id>              Disable an ingress peer")
}

// PrintExportUsage provides specific help for the 'export' command
func PrintExportUsage() {
	fmt.Println("Usage: netbird-manage export [options] [output-file]")
	fmt.Println("\nExport configuration to YAML file.")
	fmt.Println("\nOptions:")
	fmt.Println("  --all                            Export all resources (default)")
	fmt.Println("  --groups                         Export only groups")
	fmt.Println("  --policies                       Export only policies")
	fmt.Println("  --setup-keys                     Export only setup keys")
	fmt.Println("  --routes                         Export only routes")
	fmt.Println("  --dns                            Export only DNS configuration")
	fmt.Println("  --posture-checks                 Export only posture checks")
	fmt.Println()
	fmt.Println("If no output file is specified, writes to stdout.")
}

// PrintImportUsage provides specific help for the 'import' command
func PrintImportUsage() {
	fmt.Println("Usage: netbird-manage import [options] <input-file>")
	fmt.Println("\nImport configuration from YAML file.")
	fmt.Println("\nOptions:")
	fmt.Println("  --apply                          Actually apply changes (default is dry-run)")
	fmt.Println("  --update                         Update existing resources")
	fmt.Println("  --skip-existing                  Skip resources that already exist")
	fmt.Println("  --force                          Create or update all resources (upsert)")
	fmt.Println("  --skip-missing-peers             Create groups without peers that don't exist yet")
	fmt.Println("  --validate-peers                 Validate that peers in config exist (no import)")
	fmt.Println("  --verbose                        Show detailed output")
	fmt.Println()
	fmt.Println("Resource Filters:")
	fmt.Println("  --groups-only                    Import only groups")
	fmt.Println("  --policies-only                  Import only policies")
	fmt.Println("  --networks-only                  Import only networks")
	fmt.Println("  --routes-only                    Import only routes")
	fmt.Println("  --dns-only                       Import only DNS nameserver groups")
	fmt.Println("  --posture-only                   Import only posture checks")
	fmt.Println("  --setup-keys-only                Import only setup keys")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  netbird-manage import config.yml                       # Dry-run preview")
	fmt.Println("  netbird-manage import config.yml --apply               # Apply changes")
	fmt.Println("  netbird-manage import config.yml --validate-peers      # Check if peers exist first")
	fmt.Println("  netbird-manage import config.yml --apply --skip-missing-peers")
	fmt.Println("                                                         # Create groups even if peers aren't registered")
	fmt.Println()
	fmt.Println("The input file should be a YAML file previously exported with 'netbird-manage export'.")
}
