package commands

import "fmt"

// PrintUsage displays the main CLI usage information
func PrintUsage() {
	fmt.Println("NetBird Management CLI")
	fmt.Println("----------------------")
	fmt.Println("A simple tool to manage your NetBird network via the API.")
	fmt.Println("\nUsage:")
	fmt.Println("  netbird-manage [--yes] [--debug] <command> [arguments]")
	fmt.Println("\nGlobal Flags:")
	fmt.Println("  --yes, -y                     Skip confirmation prompts (for automation)")
	fmt.Println("  --debug, -d                   Enable verbose debug output (HTTP requests/responses)")
	fmt.Println("\nAvailable Commands:")
	fmt.Println("  connect                       Check current connection status")
	fmt.Println("  connect [flags]               Connect and save your API token")
	fmt.Println("    --token <key>               (Required) Your NetBird API token")
	fmt.Println("    --management-url <url>      (Optional) Your self-hosted management URL")
	fmt.Println()
	fmt.Println("  peer ...                      Manage peers (run 'netbird-manage peer' for options)")
	fmt.Println()
	fmt.Println("  group ...                     Manage groups (run 'netbird-manage group' for options)")
	fmt.Println()
	fmt.Println("  network ...                   Manage networks (run 'netbird-manage network' for options)")
	fmt.Println()
	fmt.Println("  policy ...                    Manage access control policies (run 'netbird-manage policy' for options)")
	fmt.Println()
	fmt.Println("  setup-key ...                 Manage device registration keys (run 'netbird-manage setup-key' for options)")
	fmt.Println()
	fmt.Println("  user ...                      Manage users and invitations (run 'netbird-manage user' for options)")
	fmt.Println()
	fmt.Println("  token ...                     Manage personal access tokens (run 'netbird-manage token' for options)")
	fmt.Println()
	fmt.Println("  route ...                     Manage network routes (run 'netbird-manage route' for options)")
	fmt.Println()
	fmt.Println("  dns ...                       Manage DNS nameserver groups (run 'netbird-manage dns' for options)")
	fmt.Println()
	fmt.Println("  dns-zone ...                  Manage custom DNS zones and records (run 'netbird-manage dns-zone' for options)")
	fmt.Println()
	fmt.Println("  posture-check ...             Manage device posture checks (run 'netbird-manage posture-check' for options)")
	fmt.Println()
	fmt.Println("  event ...                     View audit logs, traffic events, and proxy logs (run 'netbird-manage event' for options)")
	fmt.Println()
	fmt.Println("  job ...                       Manage peer jobs like debug bundles (run 'netbird-manage job' for options)")
	fmt.Println()
	fmt.Println("  notification ...              Manage notification channels (run 'netbird-manage notification' for options)")
	fmt.Println()
	fmt.Println("  geo ...                       Retrieve geographic location data (run 'netbird-manage geo' for options)")
	fmt.Println()
	fmt.Println("  account ...                   Manage account settings (run 'netbird-manage account' for options)")
	fmt.Println()
	fmt.Println("  ingress-port ...              Manage port forwarding - Cloud-only (run 'netbird-manage ingress-port' for options)")
	fmt.Println()
	fmt.Println("  ingress-peer ...              Manage ingress peers - Cloud-only (run 'netbird-manage ingress-peer' for options)")
	fmt.Println()
	fmt.Println("  export ...                    Export configuration to YAML (run 'netbird-manage export' for options)")
	fmt.Println()
	fmt.Println("  import ...                    Import configuration from YAML (run 'netbird-manage import' for options)")
	fmt.Println()
	fmt.Println("  migrate ...                   Migrate peers between accounts (run 'netbird-manage migrate' for options)")
	fmt.Println()
	fmt.Println("  help                          Show this help message")
}

// PrintPeerUsage provides specific help for the 'peer' command
func PrintPeerUsage() {
	fmt.Println("Usage: netbird-manage peer <flag> [arguments]")
	fmt.Println("\nManage network peers.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                            List all peers")
	fmt.Println("    --filter-name <pattern>         Filter by name (supports wildcards: ubuntu*)")
	fmt.Println("    --filter-ip <pattern>           Filter by IP address pattern")
	fmt.Println("  --inspect <peer-id>               Inspect a single peer")
	fmt.Println("  --accessible-peers <peer-id>      List peers accessible from the specified peer")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --remove <peer-id>                Remove a peer from your network")
	fmt.Println("  --remove-batch <id1,id2,...>      Remove multiple peers (comma-separated IDs)")
	fmt.Println()
	fmt.Println("  --edit <peer-id>                  Edit peer group membership")
	fmt.Println("    --add-group <group-id>          Add peer to a group (requires --edit)")
	fmt.Println("    --remove-group <group-id>       Remove peer from a group (requires --edit)")
	fmt.Println()
	fmt.Println("  --update <peer-id>                Update peer settings")
	fmt.Println("    --rename <new-name>             Change peer name")
	fmt.Println("    --ssh-enabled <true|false>      Enable/disable SSH access")
	fmt.Println("    --login-expiration <true|false> Enable/disable login expiration")
	fmt.Println("    --inactivity-expiration <true|false> Enable/disable inactivity expiration")
	fmt.Println("    --approval-required <true|false> Require approval (cloud-only)")
	fmt.Println("    --ip <ip-address>               Set IP (must be in 100.64.0.0/10 range)")
	fmt.Println("    --ipv6 <ipv6-address>           Set IPv6 address")
	fmt.Println()
	fmt.Println("  --temporary-access <peer-id>      Create a temporary access peer")
	fmt.Println("    --name <name>                   Name for the temporary peer (required)")
	fmt.Println("    --wg-pub-key <key>              WireGuard public key (required)")
	fmt.Println("    --rules <r1,r2,...>             Comma-separated rules (required)")
}

// PrintGroupUsage provides specific help for the 'group' command
func PrintGroupUsage() {
	fmt.Println("Usage: netbird-manage group <flag> [arguments]")
	fmt.Println("\nManage network groups.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all groups")
	fmt.Println("    --filter-name <pattern>        Filter by name (supports wildcards: prod-*)")
	fmt.Println("  --inspect <group-id>             Inspect a specific group")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <group-name>            Create a new group")
	fmt.Println("    --peers <id1,id2,...>          (Optional) Add peers on creation")
	fmt.Println()
	fmt.Println("  --delete <group-id>              Delete a group")
	fmt.Println("  --delete-batch <id1,id2,...>     Delete multiple groups (comma-separated IDs)")
	fmt.Println("  --delete-unused                  Delete all unused groups (no peers, resources, or references)")
	fmt.Println()
	fmt.Println("  --rename <group-id>              Rename a group")
	fmt.Println("    --new-name <new-name>          New name for the group (required)")
	fmt.Println()
	fmt.Println("  --add-peers <group-id>           Add peers to a group (bulk)")
	fmt.Println("    --peers <id1,id2,...>          Comma-separated peer IDs (required)")
	fmt.Println()
	fmt.Println("  --remove-peers <group-id>        Remove peers from a group (bulk)")
	fmt.Println("    --peers <id1,id2,...>          Comma-separated peer IDs (required)")
}

// PrintNetworkUsage provides specific help for the 'network' command
func PrintNetworkUsage() {
	fmt.Println("Usage: netbird-manage network <flag> [arguments]")
	fmt.Println("\nManage networks, resources, and routers.")
	fmt.Println("\n=== Network Operations ===")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                              List all networks")
	fmt.Println("    --filter-name <pattern>           Filter by name (supports wildcards: prod-*)")
	fmt.Println("  --inspect <network-id>              Inspect a specific network")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                     Create a new network")
	fmt.Println("    --description <desc>              Network description (optional)")
	fmt.Println()
	fmt.Println("  --delete <network-id>               Delete a network")
	fmt.Println()
	fmt.Println("  --rename <network-id>               Rename a network")
	fmt.Println("    --new-name <name>                 New name (required)")
	fmt.Println()
	fmt.Println("  --update <network-id>               Update network description")
	fmt.Println("    --description <desc>              New description (required)")
	fmt.Println()
	fmt.Println("\n=== Resource Operations ===")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list-resources <network-id>       List all resources in a network")
	fmt.Println("  --inspect-resource                  Inspect a specific resource")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --resource-id <id>                Resource ID (required)")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --add-resource <network-id>         Add a resource to a network")
	fmt.Println("    --name <name>                     Resource name (required)")
	fmt.Println("    --address <address>               IP (1.1.1.1), subnet (192.168.0.0/24), or domain (*.example.com) (required)")
	fmt.Println("    --groups <id1,id2,...>            Comma-separated group IDs (required)")
	fmt.Println("    --description <desc>              Resource description (optional)")
	fmt.Println("    --enabled                         Enable resource (default)")
	fmt.Println("    --disabled                        Disable resource")
	fmt.Println()
	fmt.Println("  --update-resource                   Update a resource")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --resource-id <id>                Resource ID (required)")
	fmt.Println("    --name <name>                     New name (optional)")
	fmt.Println("    --address <address>               New address (optional)")
	fmt.Println("    --groups <id1,id2,...>            New groups (optional)")
	fmt.Println("    --description <desc>              New description (optional)")
	fmt.Println("    --enabled/--disabled              Toggle enabled status")
	fmt.Println()
	fmt.Println("  --remove-resource                   Remove a resource")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --resource-id <id>                Resource ID (required)")
	fmt.Println()
	fmt.Println("\n=== Router Operations ===")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list-routers <network-id>         List all routers in a network")
	fmt.Println("  --list-all-routers                  List all routers across all networks")
	fmt.Println("  --inspect-router                    Inspect a specific router")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --router-id <id>                  Router ID (required)")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --add-router <network-id>           Add a router to a network")
	fmt.Println("    --peer <peer-id>                  Use single peer as router (use this OR --peer-groups)")
	fmt.Println("    --peer-groups <id1,id2,...>       Use peer groups as routers (use this OR --peer)")
	fmt.Println("    --metric <1-9999>                 Route metric, lower = higher priority (default: 100)")
	fmt.Println("    --masquerade                      Enable masquerading (NAT)")
	fmt.Println("    --no-masquerade                   Disable masquerading (default)")
	fmt.Println("    --enabled                         Enable router (default)")
	fmt.Println("    --disabled                        Disable router")
	fmt.Println()
	fmt.Println("  --update-router                     Update a router")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --router-id <id>                  Router ID (required)")
	fmt.Println("    --peer <peer-id>                  Change to single peer (optional)")
	fmt.Println("    --peer-groups <id1,id2,...>       Change to peer groups (optional)")
	fmt.Println("    --metric <1-9999>                 Update metric (optional)")
	fmt.Println("    --masquerade/--no-masquerade      Toggle masquerading")
	fmt.Println("    --enabled/--disabled              Toggle enabled status")
	fmt.Println()
	fmt.Println("  --remove-router                     Remove a router")
	fmt.Println("    --network-id <id>                 Network ID (required)")
	fmt.Println("    --router-id <id>                  Router ID (required)")
}

// PrintPolicyUsage provides specific help for the 'policy' command
func PrintPolicyUsage() {
	fmt.Println("Usage: netbird-manage policy <flag> [arguments]")
	fmt.Println("\nManage access control policies.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all policies")
	fmt.Println("  --inspect <policy-id>            Inspect a specific policy")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create a new policy")
	fmt.Println("    --description <desc>           Policy description (optional)")
	fmt.Println("    --enabled                      Enable policy (default)")
	fmt.Println("    --disabled                     Create disabled policy")
	fmt.Println()
	fmt.Println("  --delete <policy-id>             Delete a policy")
	fmt.Println()
	fmt.Println("  --enable <policy-id>             Enable a policy")
	fmt.Println("  --disable <policy-id>            Disable a policy")
	fmt.Println()
	fmt.Println("  --add-rule <policy-id>           Add a rule to a policy")
	fmt.Println("    --rule-name <name>             Rule name (required)")
	fmt.Println("    --sources <groups>             Source group IDs/names (comma-separated)")
	fmt.Println("    --destinations <groups>        Destination group IDs/names (comma-separated)")
	fmt.Println("    --protocol <protocol>          Protocol: all, tcp, udp, icmp, netbird-ssh (default: all)")
	fmt.Println("    --ports <ports>                Ports: 80,443 or 8000-9000 (optional)")
	fmt.Println("    --action <action>              Action: accept or drop (default: accept)")
	fmt.Println("    --bidirectional                Enable bidirectional traffic (default)")
	fmt.Println("    --unidirectional               Disable bidirectional traffic")
}

// PrintSetupKeyUsage provides specific help for the 'setup-key' command
func PrintSetupKeyUsage() {
	fmt.Println("Usage: netbird-manage setup-key <flag> [arguments]")
	fmt.Println("\nManage device registration/setup keys.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all setup keys")
	fmt.Println("  --inspect <key-id>               Inspect a specific setup key")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create a new setup key")
	fmt.Println("    --type <type>                  Key type: one-off or reusable (default: one-off)")
	fmt.Println("    --expires-in <days>            Expiration in days (default: 30)")
	fmt.Println("    --usage-limit <limit>          Max uses for reusable keys (default: 0 = unlimited)")
	fmt.Println("    --auto-groups <groups>         Comma-separated group IDs/names for auto-assignment")
	fmt.Println("    --ephemeral                    Create ephemeral peers (auto-removed when offline)")
	fmt.Println()
	fmt.Println("  --quick-create                   Quickly create a one-off key with defaults")
	fmt.Println("    --auto-groups <groups>         (Optional) Auto-assign groups")
	fmt.Println()
	fmt.Println("  --delete <key-id>                Delete a setup key")
	fmt.Println("  --delete-batch <id1,id2,...>     Delete multiple keys (comma-separated IDs)")
	fmt.Println("  --delete-all                     Delete ALL setup keys (requires confirmation)")
	fmt.Println()
	fmt.Println("  --revoke <key-id>                Revoke a setup key (disable without deleting)")
}

// PrintUserUsage provides specific help for the 'user' command
func PrintUserUsage() {
	fmt.Println("Usage: netbird-manage user <flag> [arguments]")
	fmt.Println("\nManage users and access.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all users")
	fmt.Println("  --inspect <user-id>              Inspect a specific user")
	fmt.Println("  --me                             Show current user info")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --invite <email>                 Invite a new user")
	fmt.Println("    --role <role>                  Role: admin, user, owner (default: user)")
	fmt.Println("    --auto-groups <groups>         Comma-separated group IDs for auto-assignment")
	fmt.Println()
	fmt.Println("  --create-service <name>          Create a service user")
	fmt.Println("    --role <role>                  Role: admin, user (default: user)")
	fmt.Println("    --auto-groups <groups>         Comma-separated group IDs for auto-assignment")
	fmt.Println()
	fmt.Println("  --update <user-id>               Update a user")
	fmt.Println("    --role <role>                  New role")
	fmt.Println("    --auto-groups <groups>         New auto-groups")
	fmt.Println()
	fmt.Println("  --block <user-id>                Block a user")
	fmt.Println("  --unblock <user-id>              Unblock a user")
	fmt.Println()
	fmt.Println("  --approve <user-id>              Approve a pending user (Cloud)")
	fmt.Println("  --reject <user-id>               Reject a pending user (Cloud)")
	fmt.Println()
	fmt.Println("  --change-password <user-id>      Change a user's password (embedded IdP)")
	fmt.Println("    --old-password <pw>            Current password (required)")
	fmt.Println("    --new-password <pw>            New password, min 8 chars (required)")
	fmt.Println()
	fmt.Println("  --remove <user-id>               Remove a user")
	fmt.Println("  --resend-invite <user-id>        Resend invitation email")
	fmt.Println()
	fmt.Println("Invite Management:")
	fmt.Println("  --list-invites                   List pending user invites")
	fmt.Println("  --create-invite                  Create a user invite")
	fmt.Println("    --email <email>                Invitee email (required)")
	fmt.Println("    --name <name>                  Invitee name (required)")
	fmt.Println("    --role <role>                  Role (default: user)")
	fmt.Println("    --auto-groups <groups>         Comma-separated group IDs")
	fmt.Println("    --expires-in <seconds>         Invite expiration")
	fmt.Println("  --delete-invite <invite-id>      Delete a pending invite")
	fmt.Println("  --regenerate-invite <invite-id>  Regenerate an invite (new token/expiry)")
}

// PrintTokenUsage provides specific help for the 'token' command
func PrintTokenUsage() {
	fmt.Println("Usage: netbird-manage token <flag> [arguments]")
	fmt.Println("\nManage personal access tokens.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all tokens for current user")
	fmt.Println("  --inspect <token-id>             Inspect a specific token")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create a new token")
	fmt.Println("    --expires-in <days>            Expiration in days (1-365, default: 30)")
	fmt.Println()
	fmt.Println("  --revoke <token-id>              Revoke/delete a token")
}

// PrintRouteUsage provides specific help for the 'route' command
func PrintRouteUsage() {
	fmt.Println("Usage: netbird-manage route <flag> [arguments]")
	fmt.Println("\nManage network routes.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all routes")
	fmt.Println("  --inspect <route-id>             Inspect a specific route")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <cidr|domains>          Create a route for a CIDR (10.0.0.0/16) or domain list (a.com,b.com)")
	fmt.Println("    --network-id <id>              Route identifier (required)")
	fmt.Println("    --peer <peer-id>               Routing peer (use this OR --peer-groups)")
	fmt.Println("    --peer-groups <ids>            Routing peer groups (comma-separated)")
	fmt.Println("    --groups <ids>                 Distribution groups (comma-separated, required)")
	fmt.Println("    --access-control-groups <ids>  Access control groups (comma-separated)")
	fmt.Println("    --metric <1-9999>              Route metric (default: 100)")
	fmt.Println("    --masquerade                   Enable masquerading")
	fmt.Println("    --keep-route <true|false>      Keep routes for resolved domain IPs")
	fmt.Println("    --skip-auto-apply <true|false> Skip auto-applying exit node route on clients")
	fmt.Println("    --description <desc>           Route description")
	fmt.Println()
	fmt.Println("  --update <route-id>              Update a route (same flags as --create, plus --domains)")
	fmt.Println("    --domains <d1,d2,...>          Replace the route's domain list")
	fmt.Println()
	fmt.Println("  --delete <route-id>              Delete a route")
	fmt.Println()
	fmt.Println("  --enable <route-id>              Enable a route")
	fmt.Println("  --disable <route-id>             Disable a route")
}

// PrintDNSUsage provides specific help for the 'dns' command
func PrintDNSUsage() {
	fmt.Println("Usage: netbird-manage dns <flag> [arguments]")
	fmt.Println("\nManage DNS nameserver groups.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all DNS nameserver groups")
	fmt.Println("  --inspect <group-id>             Inspect a specific DNS group")
	fmt.Println("  --get-settings                   Show DNS settings")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create a DNS nameserver group")
	fmt.Println("    --nameservers <ips>            Comma-separated nameserver IPs (required)")
	fmt.Println("    --groups <ids>                 Distribution groups (comma-separated, required)")
	fmt.Println("    --domains <domains>            Match domains (comma-separated, optional)")
	fmt.Println("    --primary                      Set as primary DNS")
	fmt.Println("    --search-domains               Enable search domains")
	fmt.Println()
	fmt.Println("  --delete <group-id>              Delete a DNS nameserver group")
	fmt.Println()
	fmt.Println("  --enable <group-id>              Enable a DNS group")
	fmt.Println("  --disable <group-id>             Disable a DNS group")
}

// PrintPostureCheckUsage provides specific help for the 'posture-check' command
func PrintPostureCheckUsage() {
	fmt.Println("Usage: netbird-manage posture-check <flag> [arguments]")
	fmt.Println("\nManage device posture checks.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all posture checks")
	fmt.Println("  --inspect <check-id>             Inspect a specific posture check")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create <name>                  Create a posture check")
	fmt.Println("    --description <desc>           Check description")
	fmt.Println("    --nb-version <version>         Minimum NetBird version")
	fmt.Println("    --geo-allow <codes>            Allow countries (comma-separated ISO codes)")
	fmt.Println("    --geo-deny <codes>             Deny countries")
	fmt.Println("    --network-allow <cidrs>        Allow network ranges")
	fmt.Println("    --network-deny <cidrs>         Deny network ranges")
	fmt.Println()
	fmt.Println("  --delete <check-id>              Delete a posture check")
}

// PrintEventUsage provides specific help for the 'event' command
func PrintEventUsage() {
	fmt.Println("Usage: netbird-manage event <flag> [arguments]")
	fmt.Println("\nView audit logs, network traffic events, and reverse proxy access logs.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --audit                          List recent audit events")
	fmt.Println("    --user-id <id>                 Filter by user ID")
	fmt.Println("    --target-id <id>               Filter by target resource ID")
	fmt.Println("    --activity-code <code>         Filter by activity code")
	fmt.Println("    --start-date <date>            Start date (ISO 8601)")
	fmt.Println("    --end-date <date>              End date (ISO 8601)")
	fmt.Println("    --search <text>                Search initiator/target names")
	fmt.Println()
	fmt.Println("  --traffic                        List network traffic events (Cloud-only, experimental)")
	fmt.Println("    --page <n>                     Page number")
	fmt.Println("    --page-size <n>                Results per page")
	fmt.Println("    --reporter-id <id>             Filter by reporting peer")
	fmt.Println("    --protocol <n>                 Filter by protocol number (6=TCP, 17=UDP)")
	fmt.Println("    --type <type>                  Filter by event type")
	fmt.Println("    --direction <dir>              Filter by traffic direction")
	fmt.Println()
	fmt.Println("  --proxy                          List reverse proxy access logs")
	fmt.Println("    --page/--page-size             Pagination")
	fmt.Println("    --source-ip <ip>               Filter by source IP")
	fmt.Println("    --host <host>                  Filter by host")
	fmt.Println("    --path <path>                  Filter by path")
	fmt.Println("    --method <method>              Filter by HTTP method")
	fmt.Println("    --status-code <code>           Filter by status code")
	fmt.Println("    --sort-by/--sort-order         Sorting")
	fmt.Println()
	fmt.Println("  --output json                    Output in JSON format")
}

// PrintGeoLocationUsage provides specific help for the 'geo' command
func PrintGeoLocationUsage() {
	fmt.Println("Usage: netbird-manage geo <flag> [arguments]")
	fmt.Println("\nRetrieve geographic location data for posture checks.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --countries                      List all available countries")
	fmt.Println("  --cities --country <country-code> List cities for a country")
	fmt.Println()
	fmt.Println("  --output <table|json>            Output format (default: table)")
}

// PrintAccountUsage provides specific help for the 'account' command
func PrintAccountUsage() {
	fmt.Println("Usage: netbird-manage account <flag> [arguments]")
	fmt.Println("\nManage account settings.")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all accounts")
	fmt.Println("  --inspect <account-id>           Inspect account settings")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --update <account-id>            Update account settings")
	fmt.Println("    --peer-login-expiration <dur>  Peer login expiration (e.g., 24h, 7d)")
	fmt.Println("    --peer-login-expiration-enabled <true|false>")
	fmt.Println("    --peer-inactivity-expiration <dur> Peer inactivity expiration (e.g., 30d)")
	fmt.Println("    --peer-inactivity-expiration-enabled <true|false>")
	fmt.Println("    --dns-domain <domain>          Network DNS domain")
	fmt.Println("    --network-range <cidr>         Network IP range")
	fmt.Println("    --network-range-v6 <cidr>      IPv6 network range")
	fmt.Println("    --routing-peer-dns-resolution-enabled <true|false>")
	fmt.Println("    --jwt-groups-enabled <true|false>")
	fmt.Println("    --jwt-groups-claim <name>      JWT claim name for groups")
	fmt.Println("    --jwt-allow-groups <groups>    Comma-separated allowed groups")
	fmt.Println("    --groups-propagation-enabled <true|false>")
	fmt.Println("    --regular-users-view-blocked <true|false>")
	fmt.Println("    --lazy-connection-enabled <true|false>")
	fmt.Println("    --peer-approval-enabled <true|false>   (Cloud-only)")
	fmt.Println("    --user-approval-required <true|false>  (Cloud-only)")
	fmt.Println("    --traffic-logging <true|false>         (Cloud-only)")
	fmt.Println()
	fmt.Println("  --delete <account-id>            Delete an account (dangerous!)")
}

// PrintIngressPortUsage provides specific help for the 'ingress-port' command
func PrintIngressPortUsage() {
	fmt.Println("Usage: netbird-manage ingress-port <flag> [arguments]")
	fmt.Println("\nManage ingress port allocations (Cloud-only).")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list --peer <peer-id>          List port allocations for a peer")
	fmt.Println("    --filter-name <name>           Filter allocations by name")
	fmt.Println("  --inspect <allocation-id>        Inspect a port allocation (requires --peer)")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create                         Create a port allocation")
	fmt.Println("    --peer <peer-id>               Peer ID (required)")
	fmt.Println("    --name <name>                  Allocation name (required)")
	fmt.Println("    --port-ranges <ranges>         Port ranges: start-end:protocol (e.g., 80:tcp,1000-2000:udp)")
	fmt.Println("    --direct-ports <count:proto>   Direct port mapping (e.g., 3:tcp)")
	fmt.Println("    --enabled <true|false>         Enable the allocation (default: true)")
	fmt.Println()
	fmt.Println("  --update <allocation-id>         Update a port allocation (requires --peer)")
	fmt.Println("    (same parameter flags as --create; unset flags keep current values)")
	fmt.Println()
	fmt.Println("  --delete <allocation-id>         Delete a port allocation (requires --peer)")
}

// PrintIngressPeerUsage provides specific help for the 'ingress-peer' command
func PrintIngressPeerUsage() {
	fmt.Println("Usage: netbird-manage ingress-peer <flag> [arguments]")
	fmt.Println("\nManage ingress peers (Cloud-only).")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all ingress peers")
	fmt.Println("  --inspect <ingress-peer-id>      Inspect a specific ingress peer")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create --peer <peer-id>        Convert a peer into an ingress peer")
	fmt.Println("    --enabled <true|false>         Enable on creation (default: true)")
	fmt.Println("    --fallback <true|false>        Mark as fallback ingress peer")
	fmt.Println()
	fmt.Println("  --update <ingress-peer-id>       Update an ingress peer")
	fmt.Println("    --enabled <true|false>         Enable/disable")
	fmt.Println("    --fallback <true|false>        Toggle fallback role")
	fmt.Println()
	fmt.Println("  --delete <ingress-peer-id>       Delete an ingress peer")
}

// PrintDNSZoneUsage provides specific help for the 'dns-zone' command
func PrintDNSZoneUsage() {
	fmt.Println("Usage: netbird-manage dns-zone <flag> [arguments]")
	fmt.Println("\nManage custom DNS zones and records.")
	fmt.Println("\nZone Flags:")
	fmt.Println("  --list                           List all DNS zones")
	fmt.Println("  --inspect <zone-id>              Inspect a zone (including records)")
	fmt.Println()
	fmt.Println("  --create                         Create a DNS zone")
	fmt.Println("    --name <name>                  Zone name (required)")
	fmt.Println("    --domain <domain>              Zone domain (required)")
	fmt.Println("    --distribution-groups <ids>    Distribution group IDs (comma-separated, required)")
	fmt.Println("    --enabled <true|false>         Enable the zone (default: true)")
	fmt.Println("    --search-domain <true|false>   Add the domain as a search domain")
	fmt.Println()
	fmt.Println("  --update <zone-id>               Update a zone (same parameter flags as --create)")
	fmt.Println("  --delete <zone-id>               Delete a zone")
	fmt.Println()
	fmt.Println("Record Flags:")
	fmt.Println("  --list-records <zone-id>         List records in a zone")
	fmt.Println("  --inspect-record <record-id>     Inspect a record (requires --zone)")
	fmt.Println()
	fmt.Println("  --add-record <zone-id>           Add a record to a zone")
	fmt.Println("    --record-name <name>           Record name (required)")
	fmt.Println("    --record-type <A|AAAA|CNAME>   Record type (required)")
	fmt.Println("    --content <content>            Record content: IP or hostname (required)")
	fmt.Println("    --ttl <seconds>                TTL (default: 300)")
	fmt.Println()
	fmt.Println("  --update-record <record-id>      Update a record (requires --zone)")
	fmt.Println("  --delete-record <record-id>      Delete a record (requires --zone)")
	fmt.Println("    --zone <zone-id>               Zone ID for record operations")
}

// PrintJobUsage provides specific help for the 'job' command
func PrintJobUsage() {
	fmt.Println("Usage: netbird-manage job <flag> [arguments]")
	fmt.Println("\nManage asynchronous peer jobs (e.g., debug bundle collection).")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list --peer <peer-id>          List jobs for a peer")
	fmt.Println("  --inspect <job-id>               Inspect a job (requires --peer)")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create --peer <peer-id>        Create a job for a peer")
	fmt.Println("    --type <type>                  Workload type (default: bundle)")
	fmt.Println("    --bundle-for-time <seconds>    Collect the bundle over this duration")
	fmt.Println("    --log-file-count <n>           Number of rotated log files to include")
	fmt.Println("    --anonymize                    Anonymize the collected bundle")
}

// PrintNotificationUsage provides specific help for the 'notification' command
func PrintNotificationUsage() {
	fmt.Println("Usage: netbird-manage notification <flag> [arguments]")
	fmt.Println("\nManage notification channels (email/webhook on account events).")
	fmt.Println("\nQuery Flags:")
	fmt.Println("  --list                           List all notification channels")
	fmt.Println("  --list-types                     List available event types")
	fmt.Println("  --inspect <channel-id>           Inspect a notification channel")
	fmt.Println()
	fmt.Println("Modification Flags:")
	fmt.Println("  --create                         Create a notification channel")
	fmt.Println("    --type <email|webhook>         Channel type (required)")
	fmt.Println("    --emails <e1,e2,...>           Recipient emails (for email channels)")
	fmt.Println("    --url <url>                    Webhook URL (for webhook channels)")
	fmt.Println("    --event-types <t1,t2,...>      Event types to notify on (required)")
	fmt.Println("    --enabled <true|false>         Enable the channel (default: true)")
	fmt.Println()
	fmt.Println("  --update <channel-id>            Update a channel (same parameter flags as --create)")
	fmt.Println("  --delete <channel-id>            Delete a channel")
}

// PrintExportUsage provides specific help for the 'export' command
func PrintExportUsage() {
	fmt.Println("Usage: netbird-manage export [options] [directory]")
	fmt.Println("\nExport configuration to YAML or JSON file.")
	fmt.Println("\nOptions:")
	fmt.Println("  --full                           Export to a single file (default)")
	fmt.Println("  --split                          Export to multiple files in a directory")
	fmt.Println("  --format <yaml|json>             Output format (default: yaml)")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  netbird-manage export                           # Export to single YAML file")
	fmt.Println("  netbird-manage export --format json             # Export to single JSON file")
	fmt.Println("  netbird-manage export --split                   # Export to multiple YAML files")
	fmt.Println("  netbird-manage export --split --format json     # Export to multiple JSON files")
	fmt.Println("  netbird-manage export /path/to/dir              # Export to specific directory")
	fmt.Println()
	fmt.Println("Output files are named: netbird-manage-export-YYMMDD.{yml,json}")
}

// PrintImportUsage provides specific help for the 'import' command
func PrintImportUsage() {
	fmt.Println("Usage: netbird-manage import [options] <input-file>")
	fmt.Println("\nImport configuration from YAML file.")
	fmt.Println()
	fmt.Println("⚠️  IMPORTANT: Peers cannot be imported via YAML.")
	fmt.Println("   Groups will be created WITHOUT peers. To migrate peers between accounts,")
	fmt.Println("   use the 'migrate' command: netbird-manage migrate --help")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  --apply                          Actually apply changes (default is dry-run)")
	fmt.Println("  --update                         Update existing resources")
	fmt.Println("  --skip-existing                  Skip resources that already exist")
	fmt.Println("  --force                          Create or update all resources (upsert)")
	fmt.Println("  --verbose                        Show detailed output")
	fmt.Println()
	fmt.Println("Resource Filters:")
	fmt.Println("  --groups-only                    Import only groups")
	fmt.Println("  --policies-only                  Import only policies")
	fmt.Println("  --networks-only                  Import only networks")
	fmt.Println("  --routes-only                    Import only routes")
	fmt.Println("  --dns-only                       Import only DNS nameserver groups")
	fmt.Println("  --posture-only                   Import only posture checks")
	fmt.Println("  --setup-keys-only                Import only setup keys")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  netbird-manage import config.yml                       # Dry-run preview")
	fmt.Println("  netbird-manage import config.yml --apply               # Apply changes")
	fmt.Println("  netbird-manage import config.yml --apply --skip-existing")
	fmt.Println("                                                         # Apply, skip existing resources")
	fmt.Println()
	fmt.Println("Peer Migration:")
	fmt.Println("  Peers must be migrated using the migrate command:")
	fmt.Println("    netbird-manage migrate --source-token <token> --dest-token <token> --peer <id>")
	fmt.Println("    netbird-manage migrate --source-token <token> --dest-token <token> --group <name>")
	fmt.Println()
	fmt.Println("The input file should be a YAML file previously exported with 'netbird-manage export'.")
}
